@echo off
setlocal enabledelayedexpansion

:: Get version from CMakeLists.txt
for /f "tokens=2 delims=()" %%a in ('findstr /c:"project(jucyaudio VERSION" CMakeLists.txt') do (
    for /f "tokens=2" %%v in ("%%a") do set VERSION=%%v
)

:: Parse version parts
for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
    set VERSION_MAJOR=%%a
    set VERSION_MINOR=%%b
    set VERSION_PATCH=%%c
)

echo ========================================
echo JucyAudio Release Build - Windows
echo Version: %VERSION%
echo ========================================
echo.

:: Clean and create releases directory
if exist releases rmdir /s /q releases
mkdir releases

:: Generate version.nsi
echo Generating version.nsi...
(
echo ; This file is auto-generated by publish.cmd. Do not edit manually.
echo ; Version information for NSIS installer scripts
echo.
echo !define CURRENT_VERSION "%VERSION%"
echo !define VERSION_MAJOR %VERSION_MAJOR%
echo !define VERSION_MINOR %VERSION_MINOR%
echo !define VERSION_PATCH %VERSION_PATCH%
echo.
echo ; Build information
echo !define BUILD_TYPE "Release"
echo !define COMPILER_ID "MSVC"
echo !define SYSTEM_NAME "Windows"
echo.
echo ; Product information
echo !define PRODUCT_NAME "JucyAudio"
echo !define PRODUCT_PUBLISHER "P-nand-Q"
echo !define PRODUCT_WEB_SITE "https://github.com/p-nand-q/jucyaudio"
echo !define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
echo !define PRODUCT_UNINST_ROOT_KEY "HKLM"
) > setup\version.nsi

echo.
echo [1/3] Building x64...
call :build_installer x64 x64
echo.

echo [2/3] Building x86...
call :build_installer x86 Win32
echo.

echo [3/3] Building ARM64...
call :build_installer arm64 ARM64
echo.

echo ========================================
echo Generating checksums...
pushd releases
certutil -hashfile "jucyaudio-%VERSION%-setup-x64.exe" SHA256 > checksums.txt
certutil -hashfile "jucyaudio-%VERSION%-setup-x86.exe" SHA256 >> checksums.txt
certutil -hashfile "jucyaudio-%VERSION%-setup-arm64.exe" SHA256 >> checksums.txt
popd
echo.
echo Release artifacts in releases\:
dir /b releases\*.exe
echo.
echo ========================================
echo JucyAudio Windows Release Complete!
echo ========================================
goto :eof

:build_installer
set ARCH=%1
set CMAKE_ARCH=%2
set CONFIG=Release

echo Building %ARCH%...
cmake -B build-%ARCH% -A %CMAKE_ARCH% -DCMAKE_BUILD_TYPE=%CONFIG%
cmake --build build-%ARCH% --config %CONFIG% --parallel %NUMBER_OF_PROCESSORS%

:: Copy themes to build output
if not exist "build-%ARCH%\%CONFIG%\themes" mkdir "build-%ARCH%\%CONFIG%\themes"
xcopy /s /y /q "themes\*" "build-%ARCH%\%CONFIG%\themes\" 2>nul

:: Create installer
echo Creating installer for %ARCH%...
pushd setup
makensis setup-%ARCH%.nsi
move "jucyaudio-%VERSION%-setup-%ARCH%.exe" "..\releases\" >nul
popd
echo Installer created: releases\jucyaudio-%VERSION%-setup-%ARCH%.exe
goto :eof
