name = "Jucy Orange Dark"

[colors]
"Label::textWhenEditingColourId"           = "#FFE0E0E0"  # Light text when editing labels/sliders
"Label::backgroundWhenEditingColourId"     = "#FF282c34"  # Dark background when editing
"ListBox::outlineColourId"                 = "#FF3e4451"  # Subtle border for lists/tables
"TabbedComponent::outlineColourId"         = "#FF3e4451"  # Subtle border
"TabbedButtonBar::tabOutlineColourId"      = "#FF3e4451"  # Tab borders
"Slider::trackColourId"                    = "#FF3e4451"
"Slider::textBoxOutlineColourId"           = "#FF3e4451"  # Dark border for slider text boxes
"ScrollBar::trackColourId"                 = "#FF3e4451"  # Dark gray for scrollbar track
"TextButton::buttonColourId"               = "#FF3e4451"  # "Off" state for buttons
"TextEditor::outlineColourId"              = "#FF3e4451"
"TreeView::linesColourId"                  = "#FF3e4451"  # The indent lines
"waveformColourId"                         = "#FFE0E0E0"  # Light gray/white waveform for dark theme
"accent"                           = "#FF000000"
"mainBackground"				   = "#FFF96E00"
"alternateBackground"			   = "#FFF98F44"
"mainForeground"				   = "#FF000000"
"disabledForeground"			   = "#FF333333"