name = "Jucy Orange Light"

[colors]
"Label::textWhenEditingColourId"           = "#FF212121"  # Dark text when editing labels/sliders
"Label::backgroundWhenEditingColourId"     = "#FFFFFFFF"  # White background when editing
"ListBox::outlineColourId"                 = "#FFC7C7CC"  # Subtle border for lists/tables
"TabbedComponent::outlineColourId"         = "#FFC7C7CC"  # Subtle border
"TabbedButtonBar::tabOutlineColourId"      = "#FFC7C7CC"  # Tab borders
"Slider::trackColourId"                    = "#FFD1D1D6"
"Slider::textBoxOutlineColourId"           = "#FFC7C7CC"  # Light border for slider text boxes
"ScrollBar::trackColourId"                 = "#FFE0E0E0"  # Light gray for scrollbar track
"TextButton::buttonColourId"               = "#FFEFEFF4"  # A very light button background
"TextEditor::outlineColourId"              = "#FFC7C7CC"
"TreeView::linesColourId"                  = "#FFD1D1D6"
"waveformColourId"                         = "#FF404040"  # Dark gray waveform for light theme
"accent"                           = "#FFFFFFFF"
"mainBackground"				   = "#FFF96E00"
"alternateBackground"			   = "#FFF98F44"
"mainForeground"				   = "#FFFFFFFF"
"disabledForeground"			   = "#FFDDDDCC"