; This file is auto-generated by CMake. Do not edit manually.
; Version information for NSIS installer scripts

!define CURRENT_VERSION "2.0.0"
!define VERSION_MAJOR 2
!define VERSION_MINOR 0
!define VERSION_PATCH 0

; Build information
!define BUILD_TYPE "Release"
!define COMPILER_ID "MSVC"
!define SYSTEM_NAME "Windows"
!define SYSTEM_PROCESSOR "AMD64"

; Product information
!define PRODUCT_NAME "JucyAudio"
!define PRODUCT_PUBLISHER "P-nand-Q"
!define PRODUCT_WEB_SITE "https://github.com/p-nand-q/jucyaudio"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
